# Generated by Django 3.1 on 2020-09-21 00:02

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('lookupcode', models.CharField(db_index=True, default='', max_length=32)),
                ('count', models.IntegerField(default=0)),
                ('createdon', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
