# Generated by Django 3.1 on 2020-09-21 00:16

from django.db import migrations

def createTestValues(apps, schema_editor):
	# Access the registers Product model
	Product = apps.get_model('register', 'Product')

	# Create the first test value
	testValue = Product(lookupcode='ExampleItem1', count=25)
	testValue.save()

	# Create the second test value
	testValue = Product(lookupcode='ExampleItem2', count=50)
	testValue.save()

	# Create the third test value
	testValue = Product(lookupcode='ExampleItem3', count=75)
	testValue.save()

class Migration(migrations.Migration):

    dependencies = [
        ('register', '0001_initial'),
    ]

    operations = [
    	migrations.RunPython(createTestValues),
    ]
