# Generated by Django 3.1 on 2020-10-27 10:17

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0002_auto_20200922_2215'),
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('transactionUUID', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('transactionCashierUUID', models.UUIDField(default='00000000-0000-0000-0000-000000000000', editable=False)),
                ('transactionTotal', models.FloatField(default=0.0)),
                ('transactionType', models.IntegerField(default=0)),
                ('transactionReferenceID', models.UUIDField(default='00000000-0000-0000-0000-000000000000', editable=False)),
                ('transactionCreationDate', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AddField(
            model_name='product',
            name='productPrice',
            field=models.FloatField(default=0.0),
        ),
        migrations.CreateModel(
            name='transactionEntry',
            fields=[
                ('entryUUID', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('productUUID', models.UUIDField(default='00000000-0000-0000-0000-000000000000', editable=False)),
                ('entryQuantity', models.IntegerField(default=0)),
                ('entryPrice', models.FloatField(default=0.0)),
                ('entryCreationDate', models.DateTimeField(auto_now_add=True)),
                ('transaction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entry', to='register.transaction')),
            ],
        ),
    ]
