# Generated by Django 3.1 on 2020-10-27 14:01

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0003_auto_20201027_1017'),
    ]

    operations = [
        migrations.CreateModel(
            name='shoppingCart',
            fields=[
                ('cartUUID', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('cartCreationDate', models.DateTimeField(auto_now_add=True)),
                ('employee', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='register.employee')),
            ],
        ),
        migrations.CreateModel(
            name='shoppingCartItems',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('itemAddedDate', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='transactionCashierUUID',
        ),
        migrations.AddField(
            model_name='transaction',
            name='transactionEmployee',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='register.employee'),
        ),
        migrations.AlterField(
            model_name='product',
            name='productPrice',
            field=models.DecimalField(decimal_places=2, max_digits=200),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='transactionTotal',
            field=models.DecimalField(decimal_places=2, max_digits=200),
        ),
        migrations.DeleteModel(
            name='transactionEntry',
        ),
        migrations.AddField(
            model_name='shoppingcartitems',
            name='product',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='register.product'),
        ),
        migrations.AddField(
            model_name='shoppingcart',
            name='products',
            field=models.ManyToManyField(to='register.shoppingCartItems'),
        ),
    ]
