# Generated by Django 3.1 on 2020-10-27 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0004_auto_20201027_1401'),
    ]

    operations = [
        migrations.AddField(
            model_name='shoppingcartitems',
            name='quantity',
            field=models.IntegerField(default=0),
        ),
    ]
